### ISSUE TITLE
Runtime error with `action` modifier

### ISSUE THREAD

**Issue by winsmith** [mainmatter/ember-promise-modals#977]
I'm getting the following runtime error after updating `ember-source` to v6.0:

```
ember.js:6711  

Error occurred:

- While rendering:
  -top-level
    application
      epm-modal-container
        epm-modal


execute @ ember.js:6711
handleException @ ember.js:6668
handleException @ ember.js:6686
throw @ ember.js:6667
evaluate @ ember.js:6357
_execute @ ember.js:6667
(anonymous) @ ember.js:6664
debug$1.runInTrackingTransaction @ ember.js:1359
execute @ ember.js:6664
rerender @ ember.js:6686
(anonymous) @ ember.js:14358
(anonymous) @ ember.js:14354
(anonymous) @ ember.js:14389
inTransaction @ ember.js:6493
_renderRoots @ ember.js:14382
_renderRootsTransaction @ ember.js:14394
_revalidate @ ember.js:14396
invoke @ ember.js:3199
flush @ ember.js:3194
flush @ ember.js:3213
_end @ ember.js:3243
end @ ember.js:3223
_run @ ember.js:3243
run @ ember.js:3223
run$1 @ ember.js:3306
_respond @ keyboard.js:29
ember.js:6667  

Error occurred:




execute @ ember.js:6667
rerender @ ember.js:6686
(anonymous) @ ember.js:14358
(anonymous) @ ember.js:14354
(anonymous) @ ember.js:14389
inTransaction @ ember.js:6493
_renderRoots @ ember.js:14382
_renderRootsTransaction @ ember.js:14394
_revalidate @ ember.js:14396
invoke @ ember.js:3199
flush @ ember.js:3194
flush @ ember.js:3213
_end @ ember.js:3243
end @ ember.js:3223
_run @ ember.js:3243
run @ ember.js:3223
run$1 @ ember.js:3306
_respond @ keyboard.js:29
ember.js:1302  Uncaught Error: The API deprecated by template-action was removed in ember-source 6.0.0. The message was: Usage of the `(action)` helper is deprecated. Migrate to native functions and function invocation.. Please see https://deprecations.emberjs.com/id/template-action for more details.
    at deprecateUntil (ember.js:1302:1)
    at ember.js:8225:1
    at Object.evaluate (ember.js:6407:1)
    at Object.evaluate (ember.js:6349:1)
    at LowLevelVM.evaluateSyscall (ember.js:6664:1)
    at LowLevelVM.evaluateInner (ember.js:6664:1)
    at LowLevelVM.evaluateOuter (ember.js:6664:1)
    at VM.next (ember.js:6711:1)
    at VM._execute (ember.js:6711:1)
    at VM.execute (ember.js:6706:1)
```

Seems like there's an `{{action` in there somewhere, probably this one: https://github.com/mainmatter/ember-promise-modals/blob/b1a33f2a35c6aa9ba2503a8ef49d99a4180469f6/packages/ember-promise-modals/src/components/epm-modal.hbs#L3

**Comment by pichfl** [comment]
Solved by #982 to be released soon.
